Update docker-compose-build.yml

diff --git a/.github/workflows/docker-compose-build.yml b/.github/workflows/docker-compose-build.yml
--- a/.github/workflows/docker-compose-build.yml
+++ b/.github/workflows/docker-compose-build.yml
@@ -98,21 +98,24 @@ jobs:
             echo "exists=false" >> $GITHUB_ENV
             echo "upload_url=$upload_url" >> $GITHUB_ENV
           fi
-
-      # Step 12: Upload release assets (the built JAR file) only if the release was created
-      - name: Upload Release Asset
-        if: env.exists == 'false'
-        run: |
-          echo "Verifying the existence of the JAR file..."
-          ls -l "./6 - CÓDIGO BACKEND/repositorio_tcc/target/"
-          if [ ! -f "./6 - CÓDIGO BACKEND/repositorio_tcc/target/repositorioDeTcc-0.0.1-SNAPSHOT.jar" ]; then
-            echo "Arquivo .jar não encontrado. Abortando o upload."
-            exit 1
-          fi
-      
-          echo "Uploading asset..."
-          curl -X POST \
-            -H "Authorization: token ${{ secrets.TOKEN }}" \
-            -H "Content-Type: application/java-archive" \
-            --data-binary @"./6 - CÓDIGO BACKEND/repositorio_tcc/target/repositorioDeTcc-0.0.1-SNAPSHOT.jar" \
-            "${{ env.upload_url }}"
+          
+          # Step 12: Upload Release Asset
+          - name: Upload Release Asset
+            if: env.exists == 'false'
+            run: |
+              echo "Verificando a existência do arquivo .jar..."
+              ls -l "./6 - CÓDIGO BACKEND/repositorio_tcc/target/"
+              
+              if [ ! -f "./6 - CÓDIGO BACKEND/repositorio_tcc/target/repositorioDeTcc-0.0.1-SNAPSHOT.jar" ]; then
+                echo "Arquivo .jar não encontrado. Abortando o upload."
+                exit 1
+              fi
+          
+              echo "Uploading asset..."
+              response=$(curl -X POST \
+                -H "Authorization: token ${{ secrets.TOKEN }}" \
+                -H "Content-Type: application/java-archive" \
+                --data-binary @"./6 - CÓDIGO BACKEND/repositorio_tcc/target/repositorioDeTcc-0.0.1-SNAPSHOT.jar" \
+                "${{ env.upload_url }}")
+          
+              echo "Response: $response"  # Mostra a resposta da API para diagnóstico
